name: WGT WTF?
favicon: null
layout_spectrum: 0.9931688392534852
typography_spectrum: 0.7904000252019614
title: The Musings of a Serial Online Golfer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.005199424922466278
  lightness: 0.7568827637005597
  saturation: 0.5787347336299717
  rhythmicContrast: 0.5315080510918051
purpose: []
